source 'https://github.com/CocoaPods/Specs.git'

target 'BackgroundUpload-CocoaLumberjack', :exclusive => true do
  pod "BackgroundUpload-CocoaLumberjack", :path => "../"
  pod "CocoaLumberjack"
  
  target 'Tests', :exclusive => true do
      
  end
  
end


