source 'https://github.com/CocoaPods/Specs.git'

target 'BackgroundUpload-CocoaLumberjack' do
  pod "BackgroundUpload-CocoaLumberjack", :path => "../"
  pod "CocoaLumberjack"
  
  target 'Tests' do
     inherit! :search_paths 
  end  
end


